//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int Note_ID { get; set; }
        public string Note1 { get; set; }
    }
}
